export const UPDATE_SEARCH_INPUT = 'UPDATE_SEARCH_INPUT';
export const ADD_BOOKS = 'ADD_BOOKS';
export const ZEROING_LIST = 'ZEROING_LIST';
export const ZEROING_SEARCH_INDEX = 'ZEROING_SEARCH_INDEX';
export const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING';